from enum import Enum

class Role(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ENGINEERING_ADMIN = "ENGINEERING_ADMIN"
    TRACTION_ADMIN = "TRACTION_ADMIN"
    SNT_ADMIN = "SNT_ADMIN"
    OPERATIONS_VIEWER = "OPERATIONS_VIEWER"
